name: vmstack
channels:
  - pytorch
  - pytorch3d
  - nvidia
  - conda-forge
  
dependencies:
  - python=3.9
  - pip=22.2.2
  - pytorch=2.1.0
  - torchvision=0.16.0
  - pytorch-cuda=11.8
  - pytorch3d=0.7.5
  - numpy=1.23.3
  - numba=0.56.4
  - scipy=1.9.1
  - py-opencv=4.6.0
  - cffi=1.15.1
  - matplotlib=3.6.1
  - h5py=3.8.0
  - hydra-core=1.2.0
  - einops=0.4.1
  - tqdm=4.64.1
  - dill=0.3.6
  - gym=0.21.0
  - imageio=2.22.0
  - imageio-ffmpeg=0.4.7
  - termcolor=2.0.1
  - tensorboard=2.10.1
  - tensorboardx=2.5.1
  - psutil=5.9.2
  - pytest=7.1.3
  - diffusers=0.11.1
  - av=10.0.0
  # trick to avoid cpu affinity issue described in https://github.com/pytorch/pytorch/issues/99625
  - llvm-openmp=14
  - pip:
    - open3d
    - entmax
    - lmdb
    - kornia>=0.7.0
    - wandb==0.17.0
    - huggingface-hub==0.24.7
    - git+https://github.com/openai/CLIP.git
    - pygame
    - imagecodecs==2022.9.26
    - flow_matching==1.0.10
    - -e .
    - mujoco==2.3.2
